In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)
print(arr[0])
print(arr[2])
print(arr + 10)
print(arr * 2)

[10 20 30 40 50]
10
30
[20 30 40 50 60]
[ 20  40  60  80 100]


In [ ]:
import pandas as pd

df = pd.DataFrame({"Name": ["Aman", "Rahul"], "Marks": [80, 90]})

print(df)
print(df["Marks"].mean())