In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)
print(arr[0])
print(arr[2])
print(arr + 10)
print(arr * 2)

[10 20 30 40 50]
10
30
[20 30 40 50 60]
[ 20  40  60  80 100]


In [2]:
import pandas as pd

df = pd.DataFrame({"Name": ["Groot", "Rocket"], "Marks": [80, 90]})

print(df)
print(df["Marks"].mean())

     Name  Marks
0   Groot     80
1  Rocket     90
85.0


In [ ]:
import matplotlib.pyplot as plt

x = [1, 2, 3, 4]
y = [10, 20, 15, 30]

plt.plot(x, y)
plt.show()