In [7]:
import numpy as np
myarr=np.array([[3,6,32,7]],np.int64)
myarr

array([[ 3,  6, 32,  7]])

In [8]:
myarr[0,1]

np.int64(6)

In [9]:
myarr.shape

(1, 4)

In [10]:
myarr.dtype

dtype('int64')

In [11]:
myarr[0,1]

np.int64(6)

In [12]:
myarr[0,1]=50
myarr

array([[ 3, 50, 32,  7]])

In [13]:
listarray=np.array([[1,2,3],[5,7,8],[2,4,9]])
listarray

array([[1, 2, 3],
       [5, 7, 8],
       [2, 4, 9]])