In [7]:
import numpy as np
myarr=np.array([[3,6,32,7]],np.int64)
myarr

array([[ 3,  6, 32,  7]])

In [8]:
myarr[0,1]

np.int64(6)

In [9]:
myarr.shape

(1, 4)

In [10]:
myarr.dtype

dtype('int64')

In [11]:
myarr[0,1]

np.int64(6)

In [12]:
myarr[0,1]=50
myarr

array([[ 3, 50, 32,  7]])

In [13]:
listarray=np.array([[1,2,3],[5,7,8],[2,4,9]])
listarray

array([[1, 2, 3],
       [5, 7, 8],
       [2, 4, 9]])

In [14]:
listarray.dtype

dtype('int64')

In [15]:
listarray.shape

(3, 3)

In [16]:
listarray.size

9

In [19]:
t= np.array({37,48,94})
t

array({48, 37, 94}, dtype=object)

In [20]:
zeros=np.zeros((2,7))
zeros

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [21]:
zeros.dtype

dtype('float64')

In [23]:
r=np.arange(12)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
lspace=np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
emp=np.empty((4,7))
emp

array([[2.22809558e-312, 2.46151512e-312, 2.41907520e-312,
        2.05833592e-312, 1.29441743e-312, 2.37663529e-312,
        2.05833592e-312],
       [2.41907520e-312, 2.56761491e-312, 1.93101617e-312,
        1.03977794e-312, 1.06099790e-312, 1.08221785e-312,
        9.33678148e-313],
       [1.12465777e-312, 1.16709769e-312, 1.18831764e-312,
        9.33678148e-313, 1.06099790e-312, 1.10343781e-312,
        1.20953760e-312],
       [1.97345609e-312, 2.12199579e-313, 2.22809558e-312,
        2.46151512e-312, 2.41907520e-312, 2.05833592e-312,
        1.42404727e-306]])

In [26]:
emp_like=np.empty_like(lspace)
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [27]:
ide=np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [28]:
arr=np.arange(44)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43])

In [31]:
arr=arr.reshape(2,22)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
        38, 39, 40, 41, 42, 43]])

In [32]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43])

In [33]:
x=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr.sum(axis=0)

array([12, 15, 18])

In [35]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [36]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [37]:
arr.flat

In [38]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [39]:
arr.ndim

2

In [40]:
arr.size

9

In [41]:
arr.nbytes

72

In [43]:
one=np.array([1,3,4,5,6,7])
one.argmax()

np.int64(5)

In [45]:
one.argmin()

np.int64(0)

In [46]:
one.argsort()

array([0, 1, 2, 3, 4, 5])

In [47]:
arr.argmin()

np.int64(0)